image: node:10

variables:
  APP: "angular-shell-schematic"

cache:
  paths:
    - node_modules

before_script:
  - node -v
  - npm -v
  - which node
  - which npm
  - npm install

stages:
  - build
  - test
  - deploy

# Build

.build:
  stage: build
  script:
    - npm run build

build-node-10:
  image: node:10
  extends: .build

build-node-11:
  image: node:11
  extends: .build

# Test

.test:
  stage: test
  script:
    - npm ci
    - npm test

test-node-10:
  image: node:10
  extends: .test

test-node-11:
  image: node:11
  extends: .test

# Deploy

publish:
  stage: deploy
    script:
        - ./publish.js
  only:
    - tags
